import Head from 'next/head'
import { Layout } from '../layouts/homePage/layout'
import Banner from '../sections/banner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
          <Banner></Banner>


      </Layout>   
    </>
  )
}
