import Head from 'next/head'
import { Layout } from '../layouts/homePage/layout'
import Banner from '../sections/banner'
import { Contact } from '../sections/contact'
import { Our } from '../sections/our'
import { LayoutHome } from '../layouts/homePage/layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner></Banner>
      <Our></Our>
      <Contact></Contact>
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return (
    <LayoutHome>

      {page}

    </LayoutHome>
  )
}
