import Head from 'next/head'
import { Layout } from '../layouts/homePage/layout'
import Banner from '../sections/banner'
import { Contact } from '../sections/contact'
import { Our } from '../sections/our'
import { ProviderComponent } from "../context/contextHome";
export default function Home() {
  return (
    <>
      <ProviderComponent>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout>
          <Banner></Banner>

          <Our></Our>
          <Contact></Contact>
        </Layout>
      </ProviderComponent>
    </>
  )
}
